#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#nelmio-api-doc:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix: /docs
#    schemes: [https]

users:
    type: rest
    resource: "@AppBundle/Resources/config/users_routes.yml"
    schemes: [https]

api_login_check:
    path: /login_check