# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    wefaves_api.event.jwt_created_listener:
        class: AppBundle\EventListener\JWTCreatedListener
        arguments:
            requestStack: '@request_stack'
            userManager: '@fos_user.user_manager.default'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
